-- MySQL Script generated by MySQL Workbench
-- 08/17/15 18:39:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema carbhejo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema carbhejo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carbhejo` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `carbhejo` ;

-- -----------------------------------------------------
-- Table `carbhejo`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carbhejo`.`user` ;

CREATE TABLE IF NOT EXISTS `carbhejo`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(100) NULL COMMENT '',
  `user_type` INT NOT NULL COMMENT '',
  `source` TINYINT(1) NOT NULL COMMENT '1-> Local, 2->FB likewise.',
  `source_id` VARCHAR(45) NULL COMMENT 'ID returned from OpenSDK',
  `status` TINYINT(1) NOT NULL COMMENT '',
  `created_time` DATETIME NOT NULL COMMENT '',
  `update_time` DATETIME NULL COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '',
  UNIQUE INDEX `user_name_UNIQUE` (`username` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carbhejo`.`user_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carbhejo`.`user_info` ;

CREATE TABLE IF NOT EXISTS `carbhejo`.`user_info` (
  `user_info_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT NULL COMMENT '',
  `fname` VARCHAR(45) NULL COMMENT '',
  `lname` VARCHAR(45) NULL COMMENT '',
  `dob` DATE NULL COMMENT '',
  `user_img` BLOB NULL COMMENT '',
  PRIMARY KEY (`user_info_id`)  COMMENT '',
  INDEX `fk_user_id_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_uinfo_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `carbhejo`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carbhejo`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carbhejo`.`country` ;

CREATE TABLE IF NOT EXISTS `carbhejo`.`country` (
  `country_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `country_name` VARCHAR(45) NOT NULL COMMENT '',
  `country_code` VARCHAR(10) NULL COMMENT '',
  `country_img` BLOB NULL COMMENT '',
  PRIMARY KEY (`country_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carbhejo`.`state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carbhejo`.`state` ;

CREATE TABLE IF NOT EXISTS `carbhejo`.`state` (
  `state_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `country_id` INT NOT NULL COMMENT '',
  `state_name` VARCHAR(45) NOT NULL COMMENT '',
  `state_code` VARCHAR(10) NULL COMMENT '',
  PRIMARY KEY (`state_id`)  COMMENT '',
  INDEX `fk_country_id_idx` (`country_id` ASC)  COMMENT '',
  CONSTRAINT `fk_state_country_id`
    FOREIGN KEY (`country_id`)
    REFERENCES `carbhejo`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carbhejo`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carbhejo`.`city` ;

CREATE TABLE IF NOT EXISTS `carbhejo`.`city` (
  `city_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `state_id` INT NOT NULL COMMENT '',
  `country_id` INT NOT NULL COMMENT '',
  `city_name` VARCHAR(45) NULL COMMENT '',
  `city_code` VARCHAR(10) NULL COMMENT '',
  PRIMARY KEY (`city_id`)  COMMENT '',
  INDEX `fk_state_id_idx` (`state_id` ASC)  COMMENT '',
  INDEX `fk_city_country_id_idx` (`country_id` ASC)  COMMENT '',
  CONSTRAINT `fk_city_state_id`
    FOREIGN KEY (`state_id`)
    REFERENCES `carbhejo`.`state` (`state_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_city_country_id`
    FOREIGN KEY (`country_id`)
    REFERENCES `carbhejo`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
